package zxcompiler;

import java.util.TreeMap;

public class ZXToken {
	public TreeMap<Integer, String> mMapTokens = new TreeMap<>();
	public static final int ZX_PRINT = 0XF5;
	public static final int ZX_STOP = 0XE2;
	public static final int SPECTRUM = 0XA3;
	public static final int ZXB_PLAY = 0XA4;
	public static final int ZXB_RND = 0XA5;
	public static final int ZXB_INKEY = 0XA6;
	public static final int ZXB_PI = 0XA7;
	public static final int ZXB_FN = 0XA8;
	public static final int ZXB_POINT = 0XA9;
	public static final int ZXB_SCREEN = 0XAA;
	public static final int ZXB_ATTR = 0XAB;
	public static final int ZXB_AT = 0XAC;
	public static final int ZXB_TAB = 0XAD;
	public static final int ZXB_VALS = 0XAE;
	public static final int ZXB_CODE = 0XAF;
	public static final int ZXB_VAL = 0XB0;
	public static final int ZXB_LEN = 0XB1;
	public static final int ZXB_SIN = 0XB2;
	public static final int ZXB_COS = 0XB3;
	public static final int ZXB_TAN = 0XB4;
	public static final int ZXB_ASN = 0XB5;
	public static final int ZXB_ACS = 0XB6;
	public static final int ZXB_ATN = 0XB7;
	public static final int ZXB_LN = 0XB8;
	public static final int ZXB_EXP = 0XB9;
	public static final int ZXB_INT = 0XBA;
	public static final int ZXB_SQR = 0XBB;
	public static final int ZXB_SGN = 0XBC;
	public static final int ZXB_ABSX = 0XBD;
	public static final int ZXB_PEEK = 0XBE;
	public static final int ZXB_IN = 0XBF;
	public static final int ZXB_USR = 0XC0;
	public static final int ZXB_STR = 0XC1;
	public static final int ZXB_CHR = 0XC2;
	public static final int ZXB_NOTX = 0XC3;
	public static final int ZXB_BIN = 0XC4;
	public static final int ZXB_ORX = 0XC5;
	public static final int ZXB_ANDX = 0XC6;
	public static final int ZXB_LINE = 0XCA;
	public static final int ZXB_THEN = 0XCB;
	public static final int ZXB_TO = 0XCC;
	public static final int ZXB_STEP = 0XCD;
	public static final int ZXB_DEFFN = 0XCE;
	public static final int ZXB_CAT = 0XCF;
	public static final int ZXB_FORMAT = 0XD0;
	public static final int ZXB_MOVE = 0XD1;
	public static final int ZXB_ERASE = 0XD2;
	public static final int ZXB_OPEN = 0XD3;
	public static final int ZXB_CLOSE = 0XD4;
	public static final int ZXB_MERGE = 0XD5;
	public static final int ZXB_VERIFY = 0XD6;
	public static final int ZXB_BEEP = 0XD7;
	public static final int ZXB_CIRCLE = 0XD8;
	public static final int ZXB_INK = 0XD9;
	public static final int ZXB_PAPER = 0XDA;
	public static final int ZXB_FLASH = 0XDB;
	public static final int ZXB_BRIGHT = 0XDC;
	public static final int ZXB_INVERSE = 0XDD;
	public static final int ZXB_OVER = 0XDE;
	public static final int ZXB_OUT = 0XDF;
	public static final int ZXB_LPRINT = 0XE0;
	public static final int ZXB_LLIST = 0XE1;
	public static final int ZXB_STOP = 0XE2;
	public static final int ZXB_READ = 0XE3;
	public static final int ZXB_DATA = 0XE4;
	public static final int ZXB_RESTORE = 0XE5;
	public static final int ZXB_NEW = 0XE6;
	public static final int ZXB_BORDER = 0XE7;
	public static final int ZXB_CONT = 0XE8;
	public static final int ZXB_CONTINUE = 0XE8;
	public static final int ZXB_DIM = 0XE9;
	public static final int ZXB_REM = 0XEA;
	public static final int ZXB_FOR = 0XEB;
	public static final int ZXB_GOSUB = 0XED;
	public static final int ZXB_INPUT = 0XEE;
	public static final int ZXB_LOAD = 0XEF;
	public static final int ZXB_LIST = 0XF0;
	public static final int ZXB_LET = 0XF1;
	public static final int ZXB_PAUSE = 0XF2;
	public static final int ZXB_NEXT = 0XF3;
	public static final int ZXB_POKE = 0XF4;
	public static final int ZXB_PRINT = 0XF5;
	public static final int ZXB_PLOT = 0XF6;
	public static final int ZXB_RUN = 0XF7;
	public static final int ZXB_SAVE = 0XF8;
	public static final int ZXB_RAND = 0XF9;
	public static final int ZXB_RANDOMIZE = 0XF9;
	public static final int ZXB_IF = 0XFA;
	public static final int ZXB_CLS = 0XFB;
	public static final int ZXB_DRAW = 0XFC;
	public static final int ZXB_CLEAR = 0XFD;
	public static final int ZXB_RETURN = 0XFE;
	public static final int ZXB_COPY = 0XFF;
	public static final int ZXB_GOTO = 0XEC;
	public static final int ZXB_SMALLERTHAN = 0xc7;
	public static final int ZXB_BIGGERTHAN = 0xc8;
	public static final int ZXB_UNEQUAL = 0xc9;
	public static final int ZXB_ENDOFCODE = 0x80;
	
	public String tokenToStr(int token) {
		String s = mMapTokens.get(token);
		if (s != null) return s;
		return "";
	}
	
	static ZXToken gzxtoken = null;
	public static ZXToken instance() {
		if (gzxtoken != null) return gzxtoken;
		gzxtoken = new ZXToken();
		return gzxtoken;
	}

	ZXToken() {
		mMapTokens.put(ZXB_GOTO, "GOTO");
		mMapTokens.put(ZXB_CLEAR, "CLEAR");
		mMapTokens.put(ZXB_VAL, "VAL");
		mMapTokens.put(ZXB_INPUT, "INPUT");
		mMapTokens.put(ZXB_LET, "LET");
		mMapTokens.put(ZXB_LOAD, "LOAD");
		mMapTokens.put(ZXB_CODE, "CODE");
		mMapTokens.put(ZXB_RANDOMIZE, "RANDOMIZE");
		mMapTokens.put(ZXB_USR, "USR");
		mMapTokens.put(ZX_PRINT, "RINT");
		mMapTokens.put(ZX_STOP, "TOP");
		mMapTokens.put(SPECTRUM, "TRUM");
		mMapTokens.put(ZXB_PLAY, "PLAY");
		mMapTokens.put(ZXB_RND, "RND");
		mMapTokens.put(ZXB_INKEY, "INKEY$");
		mMapTokens.put(ZXB_PI, "PI");
		mMapTokens.put(ZXB_FN, "FN");
		mMapTokens.put(ZXB_POINT, "POINT");
		mMapTokens.put(ZXB_SCREEN, "SCREEN");
		mMapTokens.put(ZXB_ATTR, "ATTR");
		mMapTokens.put(ZXB_AT, "AT");
		mMapTokens.put(ZXB_TAB, "TAB");
		mMapTokens.put(ZXB_VALS, "VALS");
		mMapTokens.put(ZXB_CODE, "CODE");
		mMapTokens.put(ZXB_VAL, "VAL");
		mMapTokens.put(ZXB_LEN, "LEN");
		mMapTokens.put(ZXB_SIN, "SIN");
		mMapTokens.put(ZXB_COS, "COS");
		mMapTokens.put(ZXB_TAN, "TAN");
		mMapTokens.put(ZXB_ASN, "ASN");
		mMapTokens.put(ZXB_ACS, "ACS");
		mMapTokens.put(ZXB_ATN, "ATN");
		mMapTokens.put(ZXB_LN, "LN");
		mMapTokens.put(ZXB_EXP, "EXP");
		mMapTokens.put(ZXB_INT, "INT");
		mMapTokens.put(ZXB_SQR, "SQR");
		mMapTokens.put(ZXB_SGN, "SGN");
		mMapTokens.put(ZXB_ABSX, "ABSX");
		mMapTokens.put(ZXB_PEEK, "PEEK");
		mMapTokens.put(ZXB_IN, "IN");
		mMapTokens.put(ZXB_USR, "USR");
		mMapTokens.put(ZXB_STR, "STR");
		mMapTokens.put(ZXB_CHR, "CHR$");
		mMapTokens.put(ZXB_NOTX, "NOT");
		mMapTokens.put(ZXB_BIN, "BIN");
		mMapTokens.put(ZXB_ORX, "OR");
		mMapTokens.put(ZXB_ANDX, "AND");
		mMapTokens.put(ZXB_LINE, "LINE");
		mMapTokens.put(ZXB_THEN, "THEN");
		mMapTokens.put(ZXB_TO, "TO");
		mMapTokens.put(ZXB_STEP, "STEP");
		mMapTokens.put(ZXB_DEFFN, "DEFFN");
		mMapTokens.put(ZXB_CAT, "CAT");
		mMapTokens.put(ZXB_FORMAT, "FORMAT");
		mMapTokens.put(ZXB_MOVE, "MOVE");
		mMapTokens.put(ZXB_ERASE, "ERASE");
		mMapTokens.put(ZXB_OPEN, "OPEN");
		mMapTokens.put(ZXB_CLOSE, "CLOSE");
		mMapTokens.put(ZXB_MERGE, "MERGE");
		mMapTokens.put(ZXB_VERIFY, "VERIFY");
		mMapTokens.put(ZXB_BEEP, "BEEP");
		mMapTokens.put(ZXB_CIRCLE, "CIRCLE");
		mMapTokens.put(ZXB_INK, "INK");
		mMapTokens.put(ZXB_PAPER, "PAPER");
		mMapTokens.put(ZXB_FLASH, "FLASH");
		mMapTokens.put(ZXB_BRIGHT, "BRIGHT");
		mMapTokens.put(ZXB_INVERSE, "INVERSE");
		mMapTokens.put(ZXB_OVER, "OVER");
		mMapTokens.put(ZXB_OUT, "OUT");
		mMapTokens.put(ZXB_LPRINT, "LPRINT");
		mMapTokens.put(ZXB_LLIST, "LLIST");
		mMapTokens.put(ZXB_STOP, "STOP");
		mMapTokens.put(ZXB_READ, "READ");
		mMapTokens.put(ZXB_DATA, "DATA");
		mMapTokens.put(ZXB_RESTORE, "RESTORE");
		mMapTokens.put(ZXB_NEW, "NEW");
		mMapTokens.put(ZXB_BORDER, "BORDER");
		mMapTokens.put(ZXB_CONT, "CONT");
		mMapTokens.put(ZXB_CONTINUE, "CONTINUE");
		mMapTokens.put(ZXB_DIM, "DIM");
		mMapTokens.put(ZXB_REM, "REM");
		mMapTokens.put(ZXB_FOR, "FOR");
		mMapTokens.put(ZXB_GOTO, "GOTO");
		mMapTokens.put(ZXB_GOSUB, "GOSUB");
		mMapTokens.put(ZXB_INPUT, "INPUT");
		mMapTokens.put(ZXB_LOAD, "LOAD");
		mMapTokens.put(ZXB_LIST, "LIST");
		mMapTokens.put(ZXB_LET, "LET");
		mMapTokens.put(ZXB_PAUSE, "PAUSE");
		mMapTokens.put(ZXB_NEXT, "NEXT");
		mMapTokens.put(ZXB_POKE, "POKE");
		mMapTokens.put(ZXB_PRINT, "PRINT");
		mMapTokens.put(ZXB_PLOT, "PLOT");
		mMapTokens.put(ZXB_RUN, "RUN");
		mMapTokens.put(ZXB_SAVE, "SAVE");
		mMapTokens.put(ZXB_RAND, "RAND");
		mMapTokens.put(ZXB_RANDOMIZE, "RANDOMIZE");
		mMapTokens.put(ZXB_IF, "IF");
		mMapTokens.put(ZXB_CLS, "CLS");
		mMapTokens.put(ZXB_DRAW, "DRAW");
		mMapTokens.put(ZXB_CLEAR, "CLEAR");
		mMapTokens.put(ZXB_RETURN, "RETURN");
		mMapTokens.put(ZXB_COPY, "COPY");
		mMapTokens.put(ZXB_GOTO, "GOTO");
		mMapTokens.put(ZXB_SMALLERTHAN, "<=");
		mMapTokens.put(ZXB_BIGGERTHAN, ">=");
		mMapTokens.put(ZXB_UNEQUAL, "<>");
	}
}
